# Each new term in the Fibonacci sequence is generated by adding the previous two
# terms. By starting with 1 and 2, the first 10 terms will be:

#     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#     By considering the terms in the Fibonacci sequence whose values do not
#     exceed four million, find the sum of the even-valued terms.

def sum_even_fibs_upto(limit):
    early = 2
    late = 8
    tot = 2
    while late < limit:
        tot += late
        tmp = late
        early, late =tmp, early + (4 * late)
    return tot

print sum_even_fibs_upto(4.e6)
